name: Deploy Lambda Functions and Glue Job

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install boto3 pandas moto

    - name: Run tests
      run: |
        python -m unittest discover tests

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Run deployment only if tests pass
    strategy:
      matrix:
        lambda:
          - name: process_trip_begin
            path: trip_handlers/process_trip_begin
          - name: process_trip_finish
            path: trip_handlers/process_trip_finish
          - name: match_and_complete
            path: trip_handlers/match_and_complete

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Zip Lambda code
      working-directory: ${{ matrix.lambda.path }}
      run: |
        zip -r ${{ matrix.lambda.name }}.zip .

    - name: Move ZIP to root for deployment
      run: |
        mv ${{ matrix.lambda.path }}/${{ matrix.lambda.name }}.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ matrix.lambda.name }} \
          --zip-file fileb://${{ matrix.lambda.name }}.zip \
          --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

  update_glue:
    runs-on: ubuntu-latest
    needs: deploy  # Run this job only after the deploy job completes
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Upload Glue script to S3
      run: |
        aws s3 cp scripts/compute_daily_metrics.py s3://nsp-bolt-trip-analytics/scripts/compute_daily_metrics.py \
          --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Update Glue Job
      run: |
        aws glue update-job \
          --job-name GenerateTripMetrics \
          --job-update '{"Role": "GlueTripRole", "Command": {"Name": "pythonshell", "ScriptLocation": "s3://nsp-bolt-trip-analytics/scripts/compute_daily_metrics.py", "PythonVersion": "3"}}' \
          --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}