name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda:
          - name: process_trip_start
            path: lambdas/process_trip_start
          - name: process_trip_end
            path: lambdas/process_trip_end
          - name: aggregate_completed_trips
            path: lambdas/aggregate_completed_trips      

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Zip Lambda code
      working-directory: ${{ matrix.lambda.path }}
      run: |
        zip -r ${{ matrix.lambda.name }}.zip .

    - name: Move ZIP to root for deployment
      run: |
        mv ${{ matrix.lambda.path }}/${{ matrix.lambda.name }}.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ matrix.lambda.name }} \
          --zip-file fileb://${{ matrix.lambda.name }}.zip \
          --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
